#!/usr/bin/python
# -*- coding: utf-8 -*-
import httplib
import json
import sys

#token = '6jH7PJLNukazh0mRaH2gu1MoNRwgSdh4TX0G4oNii0lUEJW54nFzZp7NgJdnSvKVWko9oGw4Sym1Cme81mTM6Q'
def getToken(corpid, corpsecret):
    params ='{}'
    headers = {"Content-Type": "application/json"}
    method = "GET"
    path="/cgi-bin/gettoken?corpid=%s&corpsecret=%s"%(corpid, corpsecret)
    print path
    http_port = '443' # '5000'
    http_ip = "qyapi.weixin.qq.com"
    status, resp = _httpRequest(method, path, params, http_ip, http_port)
    return resp['access_token']


def sendMessage(token = None, user='all', title='test title', message='test message'):
    print type(message)
    #messages = '[title]:'+title+"   "+'[message]:'+message
    messages = message
    #params = '{"touser": \"@%s\"%user,"toparty": \"@%s\"%user,"totag":\"@%s\"%user,"msgtype":"text","agentid": "2","text":{ "content": \"%s\"},"safe":"0"}'%messages
    param = u'{"touser": "@%s","toparty": "@%s","totag":"@%s","msgtype":"text","agentid": "2","text":{ "content": \"%s\"},"safe":"0"}'%(user,user,user, messages)
    params=param.encode('utf-8')
    print params
    headers = {"Content-Type": "application/json"}
    method = "POST"
    path = "/cgi-bin/message/send?access_token=%s"%token
    print path
    http_port = '443' 
    http_ip = "qyapi.weixin.qq.com"
    status, resp = _httpRequest(method, path, params, http_ip, http_port)
    print resp
    print status
    return status

def _httpRequest(method, path, params, http_ip, http_port):
    headers = {"Content-Type": "application/json"}
    conn = httplib.HTTPSConnection(http_ip,http_port)
    conn.request(method, path, params, headers)
    response = conn.getresponse()
    print response
    print 'show response'
    data = response.read()
    verify_services = json.loads(data)
    conn.close()
    return response.status, verify_services

def main(toUser='all', toTitle='test title', toMessage='test message', corpid=None, corpsecret=None):
    message = 'test123 lalalala'
    token = getToken(corpid, corpsecret)
    print token
    sendMessage(token, toUser, toTitle, toMessage)


if __name__== "__main__":
    corpid='wx2ebd57290f8af1ad'
    corpsecret='aZh8165A1qP7ltq858y0iDkIJisgaVwzpuaLdVURKIs6bMp7Tna950Dty4DvZHcN'
    if len(sys.argv)>=4:
        toUser = sys.argv[1]
        toTitle = sys.argv[2]

        u = '拉拉拉'
        uu = u.decode('utf8')
        print uu
        #toMessage = unicode(sys.argv[3],'utf-8')
        #toMessage = sys.argv[3].encode("utf-8")
        #msg = u"今天天氣真好"
        msg = u"aaaa"
        #toMessage =  msg.encode("utf-8")
        toMessage = u
        print toMessage
        if len(sys.argv)==6:
            corpid=sys.argv[4]
            corpsecret=sys.argv[5]
            
        main(toUser, toTitle, toMessage, corpid, corpsecret)
    else:
        print 'not enough input argument'


